<?php include_once 'access.inc' ?>  
    <div class="hero-unit">
        <h1>Ikusi zure Alarmak</h1>
        <p>Hau hautatuz gero zure alarmak ikusi ditzakezu.</p>
        <p><a class="btn btn-primary btn-large" href="erabiltzaile.php?alarmak">ikusi zure alarmak &raquo;</a></p>
    </div><!--/hero-unit-->

      <div class="row">
    
        <div class="span4">
          <h2>Sentsoreak</h2>
          <p>Zure Alarmak eta sentsoreak ikusi ditzakezu </p>
          <p><a class="btn" href="erabiltzaile.php?sentsoreak">Ikusi sentsoreak &raquo;</a></p>
       </div>
  <div class="span4">
          <h2>Alarma Berria</h2>
          <p>Hemen Alarma berria sortu dezakezu</p>
          <p><a class="btn" href="erabiltzaile.php?berria">Alarma sortu &raquo;</a></p>
        </div>

        <div class="span4">
          <h2>Beste erabiltzaileak</h2>
          <p></p>
          <p><a class="btn" href="erabiltzaile.php?erab">Ikusi erabiltzaileak &raquo;</a></p>
        </div>
         
        </div><!--/row-->

        <div class="row">
        <div class="span4">
          <h2>Alarmak konpartitu</h2>
          <p>Zure alarmak kudeatzeko baimenak eman beste erabiltzaileei</p>
          <p><a class="btn" href="erabiltzaile.php?alarmak">Alarmak konpartitu &raquo;</a></p>
        </div>   
       <div class="span4">
          <h2>Zer da?</h2>
          <p>Alarma sistema honen xehetasunak irakurri ditzakezu (Deskribapena) </p>
          <p><a class="btn" href="erabiltzaile.php?zerda">Ikusi Zer den &raquo;</a></p>
         </div>
        <div class="span4">
          <h2>Irten</h2>
          <p>Hemen sakatuta erabiltzaile gunetik atera zaitezke </p>
          <p><a class="btn" href="./erabiltzaile.php?irten">Agur!! &raquo;</a></p>
       </div>
      </div><!--/row-->

