<!-- zuzenean atzitu ahal ez izateko zerbait egin behar da!!!-->
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<a class="brand" href="./erabiltzaile.php"><?php echo $_SESSION["erab"]; ?>! </a>
		<a class="brand" href="./erabiltzaile.php?alarmak">Nire Alarmak</a>
		<a class="brand" href="./erabiltzaile.php?sentsoreak">Nire sentsoreak</a>
		<a class="brand" href="./erabiltzaile.php?berria">Sortu Alarma!</a>
		<a class="brand" href="./erabiltzaile.php?zerda">Zer da?</a>
		<a class="brand" href="./erabiltzaile.php?irten">irten</a>
	</div>
</div>
