<!-- Oina -->
<div id="footer">
	<div class="container">
		<p class="pull-right">
			<a href="#"><img src="./irudiak/go_top.png" width="48" alt="Itzuli Gora"></img></a>
		</p>
		<p>Sare eta zerbitzu aplikazioak Praktika 
			&middot; 
			<a onclick="target='_blank';" href="http://eu.wikipedia.org/wiki/Copyleft">©</a>
 			&middot; 
			<a onclick="target='_blank';" href="http://utolosa.no-ip.biz">Honi buruz</a>
			&middot; 
			<a onclick="target='_blank';" href="mailto:utolosa002@gmail.com">Kontaktua</a>  
      		</p>
       </div>
</div>
<!-- Oina -->
