<!-- Oina -->
<div id="footer">
	<div class="container">
		<p class="pull-right">
			<a href="#"><img src="http://tolosa.w.pw/irudiak/go_top.png" width="48" alt="Itzuli Gora"></img></a>
		</p>
		<p>Sare eta zerbitzu aplikazioak Praktika 
			&middot; 
			<a onclick="target='_blank';" href="http://eu.wikipedia.org/wiki/Copyleft">©</a>
 			&middot; 
			<a onclick="target='_blank';" href="http://tolosa.w.pw">Honi buruz</a>
			&middot; 
			<a onclick="target='_blank';" href="mailto:utolosa002@gmail.com">Unai Kontaktua</a>  
      	&middot; 
			<a onclick="target='_blank';" href="mailto:odei1993@gmail.com">Odei Kontaktua</a>  
      		</p>
       </div>
</div>
<!-- Oina -->
