<h1>Alarma kudeatzailea</h1>
<h3>Sare zerbitzuak eta aplikazioak</h3>
<p>Hau alarmak kudeatzeko web sistema da.</p>
<p>Web zerbitzari honek erabiltzaile bakoitzari bere alarmak kudeatzeko aukera ematen dio. Bertan lehenik eta behin erregistratu egin behar da. Behin hori eginda sortu berri dugun erabiltzaileaz saioa hasi eta alarmak kudeatzen hasi gaitezke.</p>
<p>Alarmak kudeatzeko orduan hainbat ekintza egin daitezke: Alarma berria sortu, alarma jo edo itzali, alarma bati sentsoreak gehitu edo kendu, sentsoreak aktibatu edo desaktibatu, alarma beste erabiltzaile batekin konpartitu...</p>
<br/>
<p>Ongi etorri alarma kudeatzailera.</p>
<p><a href="/">http://tolosa.w.pw</a></p>
<br/>
<p>Unai Tolosa eta Odei Ayastuy</p>
<p>Euskal Herrian, 2013ko Abenduak 10ean</p>
<br/>
